name: CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl docker

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - uses: getong/elasticsearch-action@v1.3
        with:
          elasticsearch version: '8.11.0'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'
      - name: get the stats
        run: curl -X Get "localhost:9200/_cluster/stats?pretty=true"
      - name: check the elasticsearch whether is running or not
        run: curl -X GET "localhost:9200/_cat/nodes?v&pretty"
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@v1
