name: CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        elasticsearch: ["6.8-SNAPSHOT", "7.x-SNAPSHOT", "8.18.0-SNAPSHOT", "9.0.0-SNAPSHOT"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Start Elasticsearch
        uses: ./elasticsearch
        with:
          security-enabled: false
          stack-version: ${{ matrix.elasticsearch }}

      - name: Elasticsearch is reachable
        run: |
          curl --verbose --show-error http://localhost:9200
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@v1
